application: simawebtest
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /home/(.*)
  static_files: home/\1
  upload:  home/(.*)
  
- url: /static/(.*)
  static_files: static/\1
  upload:  static/(.*)

  
- url: .*
  script: main.app
